  'use client'
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '../../app/lib/utils';
import DashboardHeader from './dashboard/_components/navbar/header';
import React, { useState } from 'react';
import Sidebar from './dashboard/_components/navbar/sidebar';
import Navbar from './dashboard/_components/navbar/header';

const inter = Inter({ subsets: ['latin'] });

{/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}; */}

export default function Dashboard({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const [isSidebarVisible, setIsSidebarVisible] = useState(false);
 

  const toggleSidebar = () => {
    setIsSidebarVisible(!isSidebarVisible);
  }; 

  const closeSidebar = () => {
    setIsSidebarVisible(false); // Function to close the sidebar on route change
  }; 

  return (
    <section
      className={cn(
        inter.className,
        'flex min-h-screen w-full  flex-col overflow-hidden ',
      )}
    >
      <DashboardHeader />
      <Sidebar  isVisible={isSidebarVisible} closeSidebar={closeSidebar} toggleSidebar={toggleSidebar}/> 
      
      <div className="flex-auto">{children}</div>
    </section>
  );
}
