  'use client'
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '../../../../lib/utils';
import DashboardHeader from './header';
import React, { useState } from 'react';
import Sidebar from './sidebar';
import Navbar from './header';
import BlackNav from './blackNav';

const inter = Inter({ subsets: ['latin'] });

{/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}; */}

export default function Dashboard({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const [isSidebarVisible, setIsSidebarVisible] = useState(false);
    const [isMobile, setIsMobile] = useState(false);
 

  const toggleSidebar = () => {
    setIsSidebarVisible(!isSidebarVisible);
  }; 

  const handleMenu = () => {
    setIsMobile(!isMobile);
  }; 

  const closeMobile = () => {
    setIsMobile(false); 
  }; 

  return (
    <section
      className={cn(
        inter.className,
        'flex min-h-screen w-full  flex-col overflow-hidden ',
      )}
    >
      <BlackNav />
      <DashboardHeader handleMenu={handleMenu}/>
      <Sidebar  isVisible={isSidebarVisible} isMobile={isMobile}  handleMenu={handleMenu} toggleSidebar={toggleSidebar}  closeMobile={closeMobile}/> 
      
      <div className="">{children}</div>
    </section>
  );
}
